# Rasa NLU Configuration for English Learning Platform

language: en

pipeline:
  # Tokenization
  - name: WhitespaceTokenizer

  # Featurization
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4

  # Intent Classification and Entity Extraction using DIET
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  # Entity Extraction
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

# Optional: Add policies for dialogue management
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
