server:
  port: 8092

spring:
  application:
    name: SpringMonolithicStarter
  datasource:
    mariadb:
      url: jdbc:mysql://localhost:3307/english_learning_platform
      username: root
      password: nam123
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: ${spring.application.name}-data
      pool-size: 30
      max-lifetime: 120
      min-idle: 5
  data:
    redis:
      host: localhost
      port: 6378
      password: 
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: nemisolv
    password: kqtgsvxoqyonuiny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  enable_seeding_db: false
  secure:
    #    auth_secret: tX+2LFhMcZjqog34U7OFc09SF/ijWXb7UrqABQ/RmD4=
    secretKey: MHQCAQEEIEYgBlyQVsH7SpHUH7x4RErcckhu7ary/JjhP72Nk19EoAcGBSuBBAAKoUQDQgAE1MtHIxlGP5TARqBccrddNm1FnYH1Fp+onETz5KbXPSeG5FGwKMUXGfAmSZJq2gENULFewwymt+9bTXkjBZhh8A==
    token-expire: 60000
    refreshToken-expire: 10080000
  mail:
    from: nemisolv@gmail.com
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
